name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8  
          
      - name: Build, Test and Publish package (.war file) to GitHub
        run: mvn -B clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Set environmental variables
        shell: bash
        run: |
          pwd
          cd target
          ls -la 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Build docker file
        shell: bash
        run: |
          pwd          
          ls -la 
          docker build -t p1docker .
          docker images

      - name: Push docker image
        shell: bash
        run: |
          aws ecr get-login-password --region region | docker login --username AWS --password-stdin 767397855923.dkr.ecr.us-east-1.amazonaws.com
          docker images
          docker tag p1docker 767397855923.dkr.ecr.us-east-1.amazonaws.com/sse:latest
          docker push 767397855923.dkr.ecr.us-east-1.amazonaws.com/sse:latest



          
      # - name: Deploy .war file to a Tomcat in Amazon EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     source: "target/petclinic.war"
      #     target: "/home/fernando/apache-tomcat-8.5.54/webapps"
      #     strip_components: 1
#Test          
